### ISSUE TITLE
WebChat V4 does not utilize conversationId

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/BotFramework-WebChat#1753]
This works as expected in WebChat V3 (Direct Line cached messages are automatically retrieved):

```js
        var convoCookie = sessionStorage.getItem("conversationId");

        if (convoCookie == null || convoCookie == 'undefined') {
            var dl = new BotChat.DirectLine({
                secret: 'token',
                webSocket: false
            });

            dl.connectionStatus$.subscribe(function (status) {
                sessionStorage.setItem('conversationId', dl.conversationId);
            });
        } else {
            var dl = new BotChat.DirectLine({
                secret: 'token',
                webSocket: false,
                conversationId: sessionStorage.getItem("conversationId"),
            });

        }

        BotChat.App({
            botConnection: dl,
            user: { id: 'userid', name: 'username' },
            bot: { id: 'botid', name: 'botname' },
            resize: 'detect'
        }, document.getElementById("bot"));
```

This does NOT work in WebChat V4:

```js
        var convoCookie = sessionStorage.getItem("conversationId");

        if (convoCookie == null || convoCookie == 'undefined') {
            var chatbot = new WebChat.createDirectLine({
                secret: 'token',
                webSocket: false,
                pollingInterval: 2000

            });
            chatbot.connectionStatus$.subscribe(function (status) {
                sessionStorage.setItem('conversationId', chatbot.conversationId);
            });
        } else {
            var chatbot = new WebChat.createDirectLine({
                secret: 'token',
                userID: 'USERID',
                conversationId: sessionStorage.getItem("conversationId"), //<-- parameter is ignored
                webSocket: false,
                pollingInterval: 2000
            });
        }

        WebChat.renderWebChat({
            directLine: chatbot,
            botAvatarInitials: ' ',
        }, document.getElementById('webchat'));
```

**Comment by corinagum** [comment]
@compulim, is resuming a conversation something that has been intentionally removed for v4? Or do we need to implement this to bring parity between v3 and v4?

**Comment by khmerforce** [comment]
@corinagum @EricDahlvang Please fix this. I really like the frontend for v4. How it has the bot icon and the suggested action doesn't block the message.

**Comment by EricDahlvang** [comment]
It looks like this has already been fixed with https://github.com/Microsoft/BotFramework-WebChat/commit/beabb417ea9bb7d20bea83e17030f9885de80216#diff-db9380a3e8a1078e72acda6485454171 

When will this fix be released?

**Comment by corinagum** [comment]
@khmerforce it looks like Eric and I had a miscommunication when we talked about this on Friday. This is fixed, as noted in the PR Eric linked above. You can use `/master/` cdn or npm to access the change immediately, or wait until the 4.3 release in the beginning of March. Sorry for the confusion!

**Comment by khmerforce** [comment]
@corinagum This is what I use but it still doesn't work. Should that have the latest code?
<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
