### ISSUE TITLE
Markdown not rendered in herocard

### ISSUE THREAD

**Issue by tdechanterac** [microsoft/BotFramework-WebChat#2147]
In the sample [01.a.getting-started-full-bundle](https://microsoft.github.io/BotFramework-WebChat/01.a.getting-started-full-bundle/) when i type "herocard", the markdown is not rendered.

![image](https://user-images.githubusercontent.com/14994711/60666446-56683200-9e67-11e9-85cd-527918590dce.png)

I'm having the same issue in my webchat component while using the latest version of the CDN.
https://cdn.botframework.com/botframework-webchat/master/webchat-es5.js
![image](https://user-images.githubusercontent.com/14994711/60666591-aba44380-9e67-11e9-89b5-e4262bdc81e8.png)

**Comment by tdurnford** [comment]
This bug has been fixed and will be available in our next release later this month. If you need these changes immediately, please see our documentation on pointing to our MyGet feed for latest bits.

https://github.com/microsoft/BotFramework-WebChat/issues/2062

**Comment by tdechanterac** [comment]
I'm still having the issue while using 
https://cdn.botframework.com/botframework-webchat/master/webchat-es5.js

Am I missing something ?

**Comment by tdurnford** [comment]
The Web Chat Development Team no longer updates the master CDN. Please use latest instead.
