### ISSUE TITLE
Speech is echoed when implemented with angular

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2926]
## Screenshots

Multiple calls being made to the custom speech endpoint
![image](https://user-images.githubusercontent.com/11289456/74904490-f1e7ec00-53d1-11ea-9814-fbbc04905a97.png)

## Version

Using webchat.js 4.7.0
Using it in angular

## Describe the bug

The output speech is getting echoed when the component is 

## Steps to reproduce

activities call to /v3/directline/conversations
and multiple calls to /cognitiveservices/v1

Additional info:

```
                                               directline           cognitiveservices
open bot once:                                   1                               1
close bot open again                             1                               2
close bot open again                             1                               3
```

and so on. Find screenshot below
The renderWebchat function is listed in the first comment

please find sample to reproduce this issue here :
[https://github.com/prashanthsridhar/WebchatSample](https://github.com/prashanthsridhar/WebchatSample)
substitute the keys as required.
Once you are on localhost,click the "click me" button, say hi,click on it again to hide the chat window. Follow this three times. The third time the reply will be hello voiced out three times
Please feel free to get back with doubts/recommendation on the implementation
## Expected behavior

No echo. That is no multiple voices.

## Additional context

Using custom voice and speech.
Implemented with angular.
connected to [2835](https://github.com/microsoft/BotFramework-WebChat/issues/2835)

**Comment by stevkan** [comment]
Hi @prashanthsridhar, please see the proposed solution in issue #2835. It should fix the issue you are experiencing. If not, please continue the conversation in that thread.

Thanks.

**Comment by prashanthsridhar** [comment]
Hi @stevkan  @tdurnford , the solution provided does not solve the issue. 
Removing speechRecognitionEndpointId and speechSynthesisDeploymentId from the code basically means no custom voice and custom speech. As provided in the additional context in the bug details we are using both. Even after removing the said properties the bug exists.

**Comment by prashanthsridhar** [comment]
Hi @stevkan @tdurnford ,this has been an issue for us for more than a month.Can you please confirm if this issue exists in webchat.

**Comment by priyanka-shetty** [comment]
I am facing something like this as well. It started behaving like this sometime in january.

**Comment by compulim** [comment]
I am trying out Web Chat 4.7.1 + Angular 8.2.14, no Custom Speech.

![image](https://user-images.githubusercontent.com/1622400/75506632-77037000-5993-11ea-88aa-075337b6031c.png)

Is it related to Custom Speech?

**Comment by prashanthsridhar** [comment]
I don't think it's related to custom speech, because when I tried after removing the keys, it was reproduced in the default tts

**Comment by prashanthsridhar** [comment]
Please check the repo mentioned in the description for easily reproducing the issue.

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/75575134-69da9580-5a14-11ea-8e65-7966fe2ef516.png)

@prashanthsridhar still didn't see it from your repo.

I didn't enable Custom Speech and custom voice font. It will take us some time to setup because we don't have any sample models.

Can you verify if it is Custom Speech or voice font?

**Comment by prashanthsridhar** [comment]
Hi @compulim, just to be extra sure, click the click me button five times before actually testing.

i tried the same without putting the recognition and speech ids.
Here are the results.
![image](https://user-images.githubusercontent.com/11289456/75661904-2ee69500-5c94-11ea-9d5c-5bb4ebbe1105.png)

**Comment by compulim** [comment]
Will look at this one over the next couple of days.

**Comment by compulim** [comment]
Sorry, lost this one from my radar, will take a look again.

**Comment by compulim** [comment]
Hi @prashanthsridhar, I am still not able to repro.

Can you look at the video I attached below to see if my repro steps are correct or not?

I have been clicking the "Click me" button 5 times to start 3 recordings, and also spam-click on it 5 times.

[bug-2926-1-mp4.zip](https://github.com/microsoft/BotFramework-WebChat/files/4529427/bug-2926-1-mp4.zip)

**Comment by cwhitten** [comment]
closing due to inactivity
