### ISSUE TITLE
Compilation errors when using non-CRA build

### ISSUE THREAD

**Issue by KarlPurk** [microsoft/BotFramework-WebChat#2974]
## Version

`botframework-webchat@4.7.1` via `npm`

## Describe the bug

I'm having problems getting the npm version to work with our build setup.  We're using a default [nx](https://github.com/nrwl/nx) generated React app.  When trying to run the build I'm seeing lots of `Module not found` errors.

Please see `Build Errors` below for the full output.

## Steps to reproduce

1. Clone the [minimal test case repository](https://github.com/KarlPurk/nx-repro-bot-framework-web-chat):
  `git clone git@github.com:KarlPurk/nx-repro-bot-framework-web-chat.git` 
2. Run the build:
  `npx @nrwl/nx build bot`

## Expected behavior

Project should build without errors.

## Additional context

I reported this on the [nx repository](https://github.com/nrwl/nx).  You can see the issue [here](https://github.com/nrwl/nx/issues/2577).

I've been able to get this working with CRA without any problems.

## Build Errors

```
➜  bot-framework-web-chat-npm git:(master) ✗ npx @nrwl/nx build bot
Starting type checking service...
Using 10 workers with 2048MB memory limit
Hash: 0d9c5f46124ebecb6461
Built at: 03/04/2020 1:13:44 PM
Entrypoint main = runtime.js runtime.js.map vendor.js vendor.js.map main.js main.js.map
Entrypoint polyfills = runtime.js runtime.js.map polyfills.js polyfills.js.map
Entrypoint styles = runtime.js runtime.js.map styles.js styles.js.map
chunk {main} main.js, main.js.map (main) 47.9 KiB ={runtime}= ={vendor}= [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 239 KiB ={runtime}= [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 0 bytes ={main}= ={polyfills}= ={styles}= ={vendor}= [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 7.75 KiB ={runtime}= [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.66 MiB ={main}= ={runtime}= [initial] [rendered] split chunk (cache group: vendor) (name: vendor)

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/jws/node_modules/jwa/index.js
Module not found: Error: Can't resolve 'crypto' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/jws/node_modules/jwa'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/replace-ext/index.js
Module not found: Error: Can't resolve 'path' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/replace-ext'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/vfile/core.js
Module not found: Error: Can't resolve 'path' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/vfile'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/observable/dom/ajax' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/observable/empty' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/observable/from' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/observable/interval' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/observable/of' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/observable/throw' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/catch' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/combineLatest' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/count' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/delay' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/do' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/mergeMap' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/retryWhen' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/share' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib/directLine.js
Module not found: Error: Can't resolve 'rxjs/add/operator/take' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/botframework-directlinejs/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/jws/lib/sign-stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/jws/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/jws/lib/verify-stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/jws/lib'

ERROR in /Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/jws/lib/data-stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/karl/SourceCode/bot-framework-web-chat-npm/node_modules/jws/lib'
```

**Comment by compulim** [comment]
Can you build with Webpack or include `node-libs-browser`?

Currently, when compile, it include Webpack's [`node-libs-browser`](https://www.npmjs.com/package/node-libs-browser) to polyfill some Node.js libraries to use in browser. Primarily from the `jsonwebtoken` dependency. I am unsure why it also fail on RxJS.

**Comment by KarlPurk** [comment]
@compulim yes we can use a node polyfill to fix the node related build errors.  The `rxjs` errors are more confusing.  

I spent a little time looking into the `rxjs` errors and I think the issue is due to module resolution.  It looks like `botframework-directlinejs` is requiring `rxjs`, for example in `botframework-directlinejs/lib/directLine.js` on line 22:

```js
require("rxjs/add/operator/catch")
```
This should be resolved with `botframework-directlinejs/node_modules/rxjs/add/operator/catch` but instead it's being resolved by `rxjs/add/operator/catch` which then tries to import `rxjs-compat/add/operator/catch` which isn't currently installed.

Installing `rxjs-compat` resolves the issue, but not the root problem of the wrong module being resolved.

**Comment by cleemullins** [comment]
Based on the comment thread above, the immediate issue is resolved.

**Comment by compulim** [comment]
@KarlPurk is `rxjs` being resolved locally? AFAIK, `botframework-directlinejs` use `rxjs@5`, and `rxjs-compat` is introduced during `@6`.

Anyway, good to see your problem is resolved.

**Comment by xtianus79** [comment]
@compulim this is still an issue as the directline package is broken. This shouldn't be happening. I don't even know what rxjs-compat is. If directly line is only compaititble with a certain version of rxjs it should bring in the packages it needs for that. When people are using rxjs 6 the expectation this npm package should work. 

Can you please reopen the issue.

**Comment by KarlPurk** [comment]
@xtianus79 I managed to fix this by updating my webpack config to polyfill crypto:

```
node: {
    crypto: true
}
```

I still needed to install `rxjs-compat` but didn't need the `node-libs-browser` polyfills.
