### ISSUE TITLE
Accessibility issue : Ensure aria-roledescription is only used on elements with an implicit or explicit role

### ISSUE THREAD

**Issue by Varshazz** [microsoft/BotFramework-WebChat#3537]
[edit by @corinagum 11/9/2020]

See latest [comment](https://github.com/microsoft/BotFramework-WebChat/issues/3537#issuecomment-724381338): I have reopened this bug due to 'layout double' and 'layout carousel' still showing as breaking accessibility in Accessibility Insights.

/end edit

---

Running a fast pass on WebChat bot, getting this error

Path | #webchat__stacked-layout__id--i5ta9

<div aria-roledescription="message" class="webchat__stacked-layout__message-row" id="webchat__stacked-layout__id--i5ta9">
**Fix the following:Give the element a role that supports aria-roledescription**

Similarly on all these:

Path | #webchat__stacked-layout__id--wpsrv
#webchat__stacked-layout__id--y6f93
#webchat__stacked-layout__id--vsynk

![image](https://user-images.githubusercontent.com/14990816/95919812-1a5a9700-0d63-11eb-88d8-9441d0fb7cec.png)

**Comment by corinagum** [comment]
@Varshazz could you add the screencaps from the email chain? Thanks.

**Comment by Varshazz** [comment]
Done. Some of the text is smudged, please ignore that.

**Comment by corinagum** [comment]
Adding this to team discussion for scheduling.

**Comment by corinagum** [comment]
Reopening issue -- unfortunately the Mock Bot commands 'layout double' and 'layout carousel' are still not showing the activities with implicit/explicit role.
