### ISSUE TITLE
[Screen Readers-Ask HR Virtual Assistant]: Screen readers(NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

### ISSUE THREAD

**Issue by kattepalli** [microsoft/BotFramework-WebChat#4395]
### Is it an issue related to Adaptive Cards?

- [X] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### Do you have any screenshots?

<img width="960" alt="Suggestion is not appropriately being announced as code information is observed on invoking Suggestion Questionnaire_Edge+NVDA (Bug 8007103)" src="https://user-images.githubusercontent.com/30458420/185468539-2be80a56-7fda-4002-8c31-19092baa2d5f.png">

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest)

### Which area does this issue affect?

Chat history

### Is this an accessibility issue?

- [X] Yes, this is an accessibility issue.

### Please describe the bug

**PWD Impact:**
Screen reader users are getting impacted if Screen readers (NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

**Test Environment:**
OS: Windows 10 version 21H1 (OS Build 19043.1110)
Browser: New Edge Version 92.0.902.62 (Official build) (64-bit)/Chrome Version 92.0.4515.107 (Official Build) (64-bit)
URL: [AskHR Virtual Assistant (azureedge.net)](https://askhrvadev.azureedge.net/?botOrigin=ec)

**Repro Steps:**
Step 1: Enable Screen readers (NVDA/JAWS) and open the above URL in the Chrome/Edge Browser using valid credentials.
Step 2: 'AskHR Virtual Assistant' Home page gets opened.
Step 3: Navigate to the list items suggestions using down arrow key and select Benefits verify the screen readers (NVDA/JAWS) behavior upon invoking the suggestion questionnaire button present in the “Ask HR Virtual Assistant” chat window.

**Actual Result:**
Screen readers (NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

Ex: NVDA/JAWS narrating as "Suggested Actions Container: Is empty………………………………complementary landmark form landmark form landmark message input box edit type your message blank Suggested Actions Container: Has content Press Alt+ Shift + A to select Laya Pension (Mercer)Well being program ESPP other benefits None of these/ask a different question "

**Expected Result:**
Screen readers(NVDA/JAWS) shouldn't narrate the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

Ex: NVDA/JAWS should narrate as "Select an option to continue this conversation Suggested Actions Container: Has content Press Alt+ Shift + A to select 6 list items button Laya, button Pension(Mercer), button Well being program, button ESPP, button other benefits, button None of these/ask a different question"

**MAS Reference:**
[MAS 4.2.1 – Object Information](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7bEEE97BBD-9990-48A0-8B03-6EA775581AA8%7d&file=MAS%204.2.1%20%E2%80%93%20Object%20Information.docx&wdLOR=cBC823FF2-F30B-4029-A49F-90FCC0AB9FEB&action=default&mobileredirect=true)

### How to reproduce the issue?

1. Navigate to ...
2. Click on ...
3. Type "Benefits" in the send box
4. select "Benefits enrollment" button.
5. observe the 

### What is the expected and actual behavior?

Expected:
Screen readers(NVDA/JAWS) shouldn't narrate the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.
Ex: NVDA/JAWS should narrate as "Select an option to continue this conversation Suggested Actions Container: Has content Press Alt+ Shift + A to select 6 list items button Laya, button Pension(Mercer), button Well being program, button ESPP, button other benefits, button None of these/ask a different question"

Actual:
Screen readers (NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.
Ex: NVDA/JAWS narrating as "Suggested Actions Container: Is empty………………………………complementary landmark form landmark form landmark message input box edit type your message blank Suggested Actions Container: Has content Press Alt+ Shift + A to select Laya Pension (Mercer)Well being program ESPP other benefits None of these/ask a different question

**Comment by kattepalli** [comment]
#A11yMAS;#A11ySev2;#HCL;#WCAG4.2.1;#Accessibility;#Win10-Edge(Chromium);#BotFrameworkWebChat-Aug21;#Linked:Bug8007103;#LinkedBug;

**Comment by v-prahu** [comment]
@ramfattah  - Do we have any tentative fix ETA for this bug.

**Comment by compulim** [comment]
This is fixed in 4.15.3. I tested this on 4.15.4.

When a bot message arrived with a few suggested action buttons, say, "Yes, I am." and "No, I am not." NVDA will narrate:

"Bot said, please select one of the actions below. Yes, I am. No, I am not. Message has suggested actions. Press ALT SHIFT A to select them."

And in Narrator, it is very similar. Bolded are different.

"Bot said, please select one of the actions below. Yes, I am, *button*. No, I am not, *button*. *Note*, message has suggested actions. Press ALT SHIFT A to select them."

**Comment by Kirank915** [comment]
@compulim As verified issue is still reproducible with NVDA. NVDA is announcing the information twice.

**Comment by Kirank915** [comment]
@compulim As verified issue is still reproducible with NVDA. NVDA is announcing the information twice. Can you please check

**Comment by Kirank915** [comment]
@compulim Issue still exists using NVDA upon invoking the Suggested Questionnaire button is being announced more than once, i.e., twice announcement is observed for NVDA
