### ISSUE TITLE
If websocket is enabled there is no chat history on page reload

### ISSUE THREAD

**Issue by rcha37** [Microsoft/BotFramework-WebChat#850]
If websockets are enabled than on page reload chat history is not getting displayed. 

The tutorial followed for getting chat history with websocket is https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-receive-activities. This works when we are using HTTP (with websockets set to false) using the botchat.js client side code. But if websocket is enabled the history is not displayed.

**Comment by kushalbhabra** [comment]
Hi, I'm facing same issue, did it get resolved for you?

**Comment by rcha37** [comment]
No issue still exists with websockets.

**Comment by rafaelmaeuer** [comment]
Is there any news on this? I would like to use websocket to avoid http pulling and to get typing bubbles. At the moment I am forced to disable websocket because I didnt found any other solution for using chat history so far. Furthermore I want to now, how chat history is stored by directline and for which amount of time? Is there another way to store chat history e.g. in my own database to restore it on page load? Then I would have full control about message data and display behaviors. And another question: will the Bot State Service deprecation (31.03.2018) affect the chat history stored by directline?

**Comment by rcha37** [comment]
There is no update yet. For chat history websocket needs to be used only for now. You can store chat history by intercepting messages https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-intercept-messages.

**Comment by vincec-msft** [comment]
A fix for this was rolled out on Direct Line earlier this month. If you're still seeing the issue please post a HAR file demonstrating the issue. Thanks.

**Comment by baki32** [comment]
Hi, 
I just tried it and I'm still not getting history after page refresh when web sockets are enabled in web chat.

**Comment by vincec-msft** [comment]
Are you sure the 2 instances of webchat are using the same conversation id?

**Comment by baki32** [comment]
Yes, it’s working fine as log as I keep webSocket param set to false

Sent from my Windows 10 phone

________________________________

**Comment by vincec-msft** [comment]
Please send the HAR file(s) to vincec@microsoft.com and I'll take a look. Thanks!

**Comment by baki32** [comment]
Sent

**Comment by baki32** [comment]
For fellow githubers I'm attaching email thread I've had so far with @vincec-msft 

----------------------------

Hi Vince,
I gave it a try without success – also I found this on DirectLineJS github

 
When I supply watermark 0 it is ignored and no history is returned after refresh. 

-------------------------
I'm not familiar enough with the webchat control to answer your question but one of my sources said, "you can provide your own watermark during initialization of BotConnection object (from DirectLineJS)."

Looks like that's specified in the DirectLineOptions (the same place the conversationid is set).

I'm not sure how much customizing is necessary, but I do know that many people customize the control extensively. The code is here:

https://github.com/Microsoft/BotFramework-WebChat

And the underlying library that handles the interaction with Direct Line is here (although changing it usually isn't necessary):

https://github.com/Microsoft/BotFramework-DirectLineJs

-------------------------------------------
We’re using webchat oob javascript code to initiate directline connection, so there’s no control over the requests. If there’s a way I don’t know about it

--------------------------------------- 
Thanks for the files.

There is a watermark parameter that controls how much of the conversation is replayed when reconnecting. That parameter is blank in the 2nd HAR file and blank means "only messages received after the reconnection request are replayed."

That default behavior is optimizing for the common case where the connection is lost due to a network blip and the client needs to reconnect, but doesn't need the history. Some conversations are very long and replaying them would be inefficient, especially if the client has to throw away messages that it already has.

Request: https://directline.botframework.com/v3/directline/conversations/JVhyhsC2O4095aIoMFPYQB?watermark=

See https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation

You can pass "watermark=-" to replay the entire conversation.

Does that help?

**Comment by vincec-msft** [comment]
Hmm, I'm not sure why DirectLineJs doesn't support a watermark on a websocket call. There's explicit code in there to block it that I'm betting could just be commented out. My familiarity is with the server side of things and I know for sure that we fixed a bug there in the last month and that a big customer is using history over websockets today. Sorry I can't be of more help, but maybe the webchat or directlinejs devs can be.

**Comment by rafaelmaeuer** [comment]
How can we get further help by webchat or directlinejs devs here?

**Comment by compulim** [comment]
@rafaelmaeuer We are working on the conversation preservation/restoration/continuation. That will help in the scenario. It is coming, just need some more time.

**Comment by compulim** [comment]
I think it is as-is for now. Web Socket does not need watermark (it's persistent connection), only HTTP Comet need watermark, thus Direct Line server preserve some history for HTTP Comet.

@rafaelmaeuer we are working on this one, you can track it in our [Projects](https://github.com/Microsoft/BotFramework-WebChat/projects) page.

**Comment by EricDahlvang** [comment]
@compulim The DirectLine connector issue with WebSocket watermarks was fixed (a few months ago).  

This PR fixes the issue with watermark and websockets in DirectLineJs (which would also fix the functionality in WebChat): https://github.com/Microsoft/BotFramework-DirectLineJS/pull/66

**Comment by corinagum** [comment]
This is related to https://github.com/Microsoft/BotFramework-WebChat/issues/365 and can be tracked there.

**Comment by keshavnagpal** [comment]
Hi, I'm still not able to use webSocket: true if I want to persist chat history by passing the conversationId.
Is there any way i can show chat history using conversationId and have webSocket=true

**Comment by eeisenbr** [comment]
I'm having the same problem.  Can this be re-opened?

**Comment by vincec-msft** [comment]
Please open a new issue and include details such as a few conversation ids and exact times that you reproed this. If the client is public then include the location. If it's not public then we can use or own webchat control to repro if we have the bot id.

**Comment by collegewap** [comment]
If someone is still facing the issue, you might be using an older version of bot framework
Passing wakermark with websocket = true was fixed in the following PR:
https://github.com/microsoft/BotFramework-DirectLineJS/pull/96

May be try bumping up the version:
https://github.com/microsoft/BotFramework-WebChat/pull/1842
